Поддержка форков
OSLL/github_repo_commitment_calc pull request #49
Opened 2024-07-19 13:43 UTC by SaveliyBorivets

2024-07-19 13:55 UTC, SaveliyBorivets commented
Пока сделана поддержка форков лишь для коммитов.
Возникает вопрос, в форках стоит выводить лишь коммиты, которых не было в исходном репозитории, или оставить всё так, как есть(все коммиты исходного репозитория, все коммиты форков, получается так, что они будут повторяться)
Если всё же нужно исключать повторения, то будет ли хорош способ сохранения всех хэшей коммитов в массив, чтобы затем проверять хэши коммитов с форков оператором in, например?

2024-07-19 13:57 UTC, SaveliyBorivets commented
Думаю, что в этой ветке можно сделать и рефракторинг кода(https://github.com/OSLL/github_repo_commitment_calc/issues/48)

2024-07-19 13:59 UTC, thehighestmath commented
Главное, чтобы всё работало)
У нас не жесткие правила разработки (ну по крайней мере у меня)), одна ветка порой может решать несколько задач. разбивать или не разбивать пеллреквест на несколько -- приходит с опытом)

2024-07-19 17:29 UTC, thehighestmath requested changes
норм

поправить несколько моментов:
1. на именах файлов можно не экономить)
2. except Exception лучше переписать
3. константы переименовать в капс
4. oracle NVL в оракле есть функция nvl https://oracleplsql.ru/nvl-function.html
кажется тут она напрашивается, чтобы вызвать её столько раз сколько нужно, а то для каждого nullable поля писать такой тернарный оператор долго :)

2024-07-19 17:29 UTC, thehighestmath commented on compars.py
> +fieldnames = ('repository name', 'author name', 'author login', 'author email', 'date and time', 'changed files', 'commit id', 'branch')
кажется это всё константы, а их принято именовать капсом

2024-07-19 17:29 UTC, thehighestmath commented on compars.py
> +def log_repository_commits(repository: Repository, csv_name, start, finish, branch):
по pep8 между функциями 2 отступа должно быть)

2024-07-19 17:29 UTC, thehighestmath commented on compars.py
> +                commit_data = [repository.full_name, commit.commit.author.name, EMPTY_FIELD, EMPTY_FIELD, commit.commit.author.date, '; '.join([file.filename for file in commit.files]), commit.commit
длинная строка, давайте сделаем 2 хотя бы)
```
commit_data = [repository.full_name, commit.commit.author.name, EMPTY_FIELD, EMPTY_FIELD,
commit.commit.author.date, '; '.join([file.filename for file in commit.files]), commit.commit.sha, branch]
```

2024-07-19 17:29 UTC, thehighestmath commented on compars.py
> +            print(e)
если рефакторим, то предлагаю не перехватывать все исключения)

2024-07-19 17:29 UTC, thehighestmath commented on invpars.py
> +                except Exception as e:
подумать)

2024-07-19 17:29 UTC, thehighestmath commented on issuepars.py
> +fieldnames = ('repository name', 'number', 'title', 'state', 'task', 'created at', 'creator name', 'creator login',
константы

2024-07-19 17:29 UTC, thehighestmath commented on issuepars.py
> +            'creator email': EMPTY_FIELD if issue.user.email is None else issue.user.email,
в оракле есть функция nvl https://oracleplsql.ru/nvl-function.html
кажется тут она напрашивается, чтобы вызвать её столько раз сколько нужно, а то для каждого nullable поля писать такой тернарный оператор долго :)

2024-07-19 17:29 UTC, thehighestmath commented on issuepars.py
> +        except Exception as e:
исключения все)

2024-07-20 09:42 UTC, thehighestmath requested changes

2024-07-20 09:42 UTC, thehighestmath commented on commits_parser.py
> +            print(e)
точно нужны все все исключения?)

2024-07-20 09:42 UTC, thehighestmath commented on invites_parser.py
> +                    print(e)
все исключения

2024-07-20 09:42 UTC, thehighestmath commented on issues_parser.py
> +                assignee_result += f"{date}: {assigner} -/> {assignee}; "
смотрю на код и кажется много чего можно упростить
1. 
```
if event.event == "assigned" or event.event == "unassigned":
  if event.event == "assigned":
  else:
```

2. кажется код в ветках ифа одинаковый, не баг ли это?

2024-07-20 09:42 UTC, thehighestmath commented on issues_parser.py
> +            'closed at': EMPTY_FIELD if issue.closed_by is None else issue.closed_at,
nvl? get_info?

2024-07-20 09:42 UTC, thehighestmath commented on issues_parser.py
> +            'labels': EMPTY_FIELD if issue.labels is None else ';'.join([label.name for label in issue.labels]),
nvl, get_info?

2024-07-20 09:42 UTC, thehighestmath commented on pull_requests_parser.py
> +                assignee_result += f"{date}: {assigner} -/> {assignee}; "
такой же код уже я видел, может стоит вынести общее в `base.py`?

2024-07-20 09:42 UTC, thehighestmath commented on pull_requests_parser.py
> +                info['comment author email'] = EMPTY_FIELD if comment.user.email is None else comment.user.email
nvl?

2024-07-20 14:29 UTC, SaveliyBorivets commented on issues_parser.py
> +                assignee_result += f"{date}: {assigner} -/> {assignee}; "
в одном просто стрелочка зачеркнута :D
-> и -/>

2024-07-20 14:33 UTC, SaveliyBorivets commented on issues_parser.py
> +            'closed at': EMPTY_FIELD if issue.closed_by is None else issue.closed_at,
вопросы по лямбда-функциям?
или поправить closed at?(тут просто ни то, ни другое не подходит, хотя я думаю, что можно просто issue.closed_at проверять)

2024-07-20 14:34 UTC, SaveliyBorivets commented on pull_requests_parser.py
> +                assignee_result += f"{date}: {assigner} -/> {assignee}; "
в git_logger перетащу

2024-07-20 14:35 UTC, SaveliyBorivets commented on issues_parser.py
> +            'labels': EMPTY_FIELD if issue.labels is None else ';'.join([label.name for label in issue.labels]),
connected pull requests и labels  через nvl или  get_info не сделать, тут тернарный оператор гораздо удобнее, чем писать отдельные функции под них

2024-07-20 14:58 UTC, thehighestmath commented on issues_parser.py
> +            'closed at': EMPTY_FIELD if issue.closed_by is None else issue.closed_at,
я про то мб тут заиспользовать что-то из этого

2024-07-20 14:58 UTC, thehighestmath commented on issues_parser.py
> +                assignee_result += f"{date}: {assigner} -/> {assignee}; "
но ради этого код дублировать -- кажется странно :/

2024-07-20 14:58 UTC, thehighestmath commented on issues_parser.py
> +            'labels': EMPTY_FIELD if issue.labels is None else ';'.join([label.name for label in issue.labels]),
ок, можно оставить

2024-07-20 14:58 UTC, thehighestmath commented on pull_requests_parser.py
> +                assignee_result += f"{date}: {assigner} -/> {assignee}; "
ок

2024-07-20 15:41 UTC, SaveliyBorivets commented on commits_parser.py
> +            print(e)
там столько команд, что даже непонятно, какие исключения могут выйти :(
пока ни разу, вроде, исключения не печатались, поэтому может try except вообще убрать?
Если всё же какие-то появятся, то потом дописать?

2024-07-20 15:42 UTC, SaveliyBorivets commented on invites_parser.py
> +                    print(e)
в обсуждении выше написал идейку

2024-07-20 16:28 UTC, thehighestmath commented on commits_parser.py
> +            print(e)
лан, оставим перехват исключений)

2024-07-20 16:29 UTC, thehighestmath commented
По коду ок
Я ещё попробую позапускать, чтобы было больше уверненности,что рефакторинг не сломал ничего (ну или не сильно сломал)

2024-07-20 16:29 UTC, thehighestmath approved these changes

2024-07-20 16:29 UTC, thehighestmath requested changes
Если после запуска кода всё будет ок, то вливаю. Пока блок

2024-07-20 17:18 UTC, SaveliyBorivets commented
Только про коммиты вопрос остался открытым. Всё-таки стоит ли выводить коммиты у форков, которые были в исходном репозитории?
Пулл реквесты, приглашения и ишью у форков, вроде как, не повторяются

2024-07-20 17:51 UTC, thehighestmath commented
Давайте выводить пока только коммиты. Если потребуется, то будем думать как
получить необходимые данные

сб, 20 июл. 2024 г., 20:18 Homie ***@***.***>:

> Только про коммиты вопрос остался открытым. Всё-таки стоит ли выводить
> коммиты у форков, которые были в исходном репозитории?
> Пулл реквесты, приглашения и ишью у форков, вроде как, не повторяются
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/OSLL/github_repo_commitment_calc/pull/49#issuecomment-2241234522>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AKHH7R43T7SRSQQINJW7GQLZNKLXNAVCNFSM6AAAAABLEUAHMKVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDENBRGIZTINJSGI>
> .
> You are receiving this because your review was requested.Message ID:
> ***@***.***>
>

2024-07-22 07:10 UTC, thehighestmath approved these changes

2024-07-22 07:11 UTC, merged